### ISSUE TITLE
Unable to load DLL 'Efferent.Native-win64.dll' or one of its dependencies On windows 32-bit system

### ISSUE THREAD

**Issue by waleswood** [Efferent-Health/fo-dicom.Codecs#10]
I am confused about why it is looking for a 64-bit library when running on a 32-bit system

``` C#
System.DllNotFoundException: Unable to load DLL 'Efferent.Native-win64.dll' or one of its dependencies:
```

Efferent.Native 4.0.0

**Comment by saydo17** [comment]
I also ran into this.  Looked in the bin/Debug folder and the Efferent.Native-win64.dll wasn't there.  When I manually copy it over, everything works.

**Comment by waleswood** [comment]
> I also ran into this. Looked in the bin/Debug folder and the Efferent.Native-win64.dll wasn't there. When I manually copy it over, everything works.

Are you sure you tried on Windows 7 32 bit? But why not use Efferent.Native.dll

**Comment by jaime-olivares** [comment]
This project doesn't work with 32 bits
