### ISSUE TITLE
Question: No support for fo-dicom 4.07?

### ISSUE THREAD

**Issue by SamirKharchi** [Efferent-Health/fo-dicom.Codecs#11]
Hi, 

the description of this project is a bit confusing. It says the codecs will be included in the upcoming fo-dicom 5. Which is nice!
Furthermore it says the library is compatible with fo-dicom 4.x , shows an example how to register the codecs with the transcode manager and even says "tested with v4.x".

However, for me, using fo-dicom.NetCore 4.07, this library is incompatible. I cannot update the transcoder implementation using `FellowOakDicom.Imaging.NativeCodec.NativeTranscoderManager()` due to the apparent differing implementation base. 

Is this using fo-dicom 5 alpha? If it's not, please let me know how to make this work with fo-dicom 4.07 or which nuget package I need to use for v4.x as it seems unapparent from the description (maybe I am missing something here..please excuse me in that case).

Cheers
Samir

**Comment by sylvainb31** [comment]
Hi Samir,

Have you found a solution ?
I have been following this : https://github.com/Efferent-Health/fo-dicom.Codecs

**Comment by sylvainb31** [comment]
Hi Samir,

Just to let you know that I have found the solution on an other issue : https://github.com/Efferent-Health/fo-dicom.Codecs/issues/8#issuecomment-642704949

The line to add is this one to make it work in your startup.cs : 
`Dicom.Imaging.Codec.TranscoderManager.SetImplementation(new Efferent.Native.Codec.NativeTranscoderManager());`

You have to add the package Efferent.Native : https://www.nuget.org/packages/Efferent.Native

**Comment by jaime-olivares** [comment]
Closing, as the answer has been provided
