### ISSUE TITLE
.netcore decompression is slow in Alpine linux docker container

### ISSUE THREAD

**Issue by jxnchk** [Efferent-Health/fo-dicom.Codecs#12]
A dicom from JPEG2000Lossy(1.3MB) to ExplicitVRLittleEndian(22MB) takes 20s in Alpine linux docker container, use .netcore.
Please help me.
Thanks

**Comment by jxnchk** [comment]
Compress also is slow from ExplicitVRLittleEndian to  JPEG2000Lossy, takes 15s. 
JPEGProcess2_4 is fast,  from ExplicitVRLittleEndian to  JPEG2000Lossy, takes 1.3s.

**Comment by jaime-olivares** [comment]
I don't think we can do something with this information.
Is there a comparison with other Linux implementations?
If there is some more info, please reopen.
