### ISSUE TITLE
Please help to change Transfer Syntax to 1.2.840.10008.1.2.4.91	JPEG 2000 Image Compression 

### ISSUE THREAD

**Issue by yadavvirus** [Efferent-Health/fo-dicom.Codecs#15]
Please help me change its transfer syntax to 1.2.840.10008.1.2.4.91	JPEG 2000 Image Compression 
I am attaching file as fo-dicom codec damaging pixels after compression.
please find the attachment.
if succeed to change transfer syntax then pls share me example code too.
I am facing same problem with new ge machine DICOM file and x-ray file too
[anny.zip](https://github.com/Efferent-Health/fo-dicom.Codecs/files/7176076/anny.zip)

**Comment by cbeltran1306** [comment]
Hi @yadavvirus, yes sure here it is a sample code for that DicomTransferSyntax
[testfodicom.zip](https://github.com/Efferent-Health/fo-dicom.Codecs/files/7186631/testfodicom.zip)

**Comment by yadavvirus** [comment]
Thank you sir for reply, Sir i have tried but i want to you to check , the attached file after changing this transfer syntax image is getting damaged in fo dicom and Efferent codec is keep on crashing. I request you please take a look in attached dicom file . Thank you

**Comment by cbeltran1306** [comment]
The attached dicom file was processed successfully, using fo-dicom and fo-dicom.Codecs 5.0.0 nuget packages references, as you can you see in the sample code

**Comment by jaime-olivares** [comment]
Hi @yadavvirus, 
Please describe your environment and share with us the code snippet you used.

**Comment by yadavvirus** [comment]
@jaime-olivares @cbeltran1306 Thank you sir for reply,
Sir above code worked but the major problem which i was facing getting image damaged in Transfer Syntax to 1.2.840.10008.1.2.4.91 JPEG 2000.
I request you to change the file which is i am providing you now in attachment.And view the image after changing it to Transfer Syntax to 1.2.840.10008.1.2.4.91 JPEG 2000.
you ll get my problem.

[anny_ct.zip](https://github.com/Efferent-Health/fo-dicom.Codecs/files/7188935/anny_ct.zip)

this is how it looks like after chaning it transfer syntax
![Capture](https://user-images.githubusercontent.com/7027914/133866789-d1d81678-66d9-4853-bacb-66db3aa42d7b.PNG)


please look into this problem. same problem was occoured in fo-dicom codecs.
Thank you

**Comment by jaime-olivares** [comment]
Thanks for sending the information. We are working on improving the JPEG2000 decoder and updating the OpenJPEG library version. After that we will come back here to see if the issue is solved.

**Comment by yadavvirus** [comment]
@jaime-olivares Thank you sir for response.

**Comment by rasindh** [comment]
With Fo-Dicom 5 and .net 4.7.2 I am using transfer syntax

1.2.840.10008.1.2.4.90 | JPEG 2000 Image Compression (Lossless Only) with an RGB image   In the receiver side If am Using Same fo-Dicom 5 no issues found. but if I send to some third party Dicom receiver it is receiving as YBR_RCT  photometricinterpretation as well as the the image is getting replicated thrice inside the same DCM. On receival the third party lib  seems to decompress and decode RGB separately and replicates thrice.

If I override while cloning just before send like below
 FellowOakDicom.Native.Codec.DicomJpeg2000Params  newParam =  new FellowOakDicom.Native.Codec.DicomJpeg2000Params() ;
                    newParam.UpdatePhotometricInterpretation = false;
                    DicomFile dicomFileObject = dicomFile.Clone(dicondeCompresionType, newParam);
am getting correct  photometric interpretation in third party lib as RGB only not getting converted to YBR_RCT.

As am new to compressed sending want to know the Correct syntax of DicomJpeg2000Params to be used. may be am not using correct params that is why third party lib is not correctly receiving  the image. With Fo-dicom 4  using same transfer syntax same third party lib was correctly receiving the image.

**Comment by Dash-Uttam** [comment]
The issue is resolved now. "Dicom.Native-win64.dll" is come when we install fo-dicom-codec. So once we install this package we need to take "Dicom.Native-win64.dll" as a reference in the References folder in VS. After doing that, need to run the project in x64 bitness, this can be done using right-click on project->select property->web->bitness:x64. By doing this we can use fo-dicom-codec for compression. I am compressing my 1gb dicom file to 100 or 200 mb and it is working fine in ORTHANC server as well.

**Comment by yadavvirus** [comment]
@Dash-Uttam  The issue is resolved now. "Dicom.Native-win64.dll" is come when we install fo-dicom-codec. So once we install this package we need to take "Dicom.Native-win64.dll" as a reference in the References folder in VS. After doing that, need to run the project in x64 bitness, this can be done using right-click on project->select property->web->bitness:x64. By doing this we can use fo-dicom-codec for compression. I am compressing my 1gb dicom file to 100 or 200 mb and it is working fine in ORTHANC server as well.
 have you tried above attached DICOM File named as

anny_ct.zip

Please try to make it compress to JPEG 2000  Lossy 1.2.840.10008.1.2.4.91
