### ISSUE TITLE
get error running on centos 7 64

### ISSUE THREAD

**Issue by 1009058470** [Efferent-Health/fo-dicom.Codecs#16]
When i used that dll for compress a dcm file and i  get this error
`[iMedPACSCompress.DcmCompress:CompressOrDeCompressDcmFile:0] ERROR - j2k 压缩或解压失败  
System.DllNotFoundException: Unable to load shared library 'Dicom.Native-linux64.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libDicom.Native-linux64.so: cannot open shared object file: No such file or directory  
   at FellowOakDicom.Native.Codec.DicomJpeg2000NativeCodec.Opj_create_compress_Linux64(OPJ_CODEC_FORMAT format)  
   at FellowOakDicom.Native.Codec.DicomJpeg2000NativeCodec.Encode(DicomPixelData oldPixelData, DicomPixelData newPixelData, DicomCodecParams parameters)  
   at FellowOakDicom.Imaging.Codec.DicomTranscoder.Encode(DicomDataset oldDataset, DicomTransferSyntax outSyntax, IDicomCodec codec, DicomCodecParams parameters)  
   at FellowOakDicom.Imaging.Codec.DicomTranscoder.Transcode(DicomDataset dataset)  
   at FellowOakDicom.Imaging.Codec.DicomCodecExtensions.Clone(DicomDataset dataset, DicomTransferSyntax syntax, DicomCodecParams parameters)  
   at iMedPACSCompress.DcmCompress.CompressOrDeCompressDcmFile(CompressType compressType, String inPath, String outPath)  
`
but i real have that file Dicom.Native-linux64.so in this floder `./runtimes/linux-x64/native/Dicom.Native-linux64.so`. 

what can i do for this error?

The code is here :

`CompressOrDeCompressDcmFile(CompressType.J2kLossLessCompress, inPath, outPath+"_j2k");

public static bool CompressOrDeCompressDcmFile(CompressType compressType, string inPath,string outPath)
        {
            bool ret = true;
            try
            {
                var transferSyntaxOfDcm = DicomTransferSyntax.ExplicitVRLittleEndian;
                if (compressType.Equals(CompressType.J2kLossLessCompress))
                    transferSyntaxOfDcm = DicomTransferSyntax.JPEG2000Lossless;
                else if (compressType.Equals(CompressType.JpegLSCompress))
                    transferSyntaxOfDcm = DicomTransferSyntax.JPEGLSLossless;
                var dcm = FellowOakDicom.DicomFile.Open(inPath);
                var original = dcm.Dataset;
                var changed = original.Clone(transferSyntaxOfDcm);
                var newdcm = new FellowOakDicom.DicomFile(changed);
                newdcm.Save(outPath);
            }
            catch(Exception ex)
            {
                ret = false;
                CLogger._log.Error("j2k 压缩或解压失败", ex);
            }
            return ret;
        }`

**it seems it lossing this file(libDicom.Native-linux64.so) on linux**

**Comment by 1009058470** [comment]
I build that with vs2019 on my windows and running that on centos 7

**Comment by cbeltran1306** [comment]
Hi @1009058470 , can you share your test project in order to check it what it is the issue?

**Comment by 1009058470** [comment]
@cbeltran1306  [here](https://github.com/1009058470/TestApp/tree/main) it is  
it can used on windows 64 but not on centos 64, it says 

`system.DllNotFoundException: Unable to load shared library **Dicom.Native-linux64.so** or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: **libDicom.Native-linux64.so**: cannot open shared object file: No such file or directory`

**Comment by jaime-olivares** [comment]
This sounds like some sort of permission or folder discovery issue

**Comment by 1009058470** [comment]
> This sounds like some sort of permission or folder discovery issue

em but i am using the root user, and i find it is truely not have libDicom.Native-linux64.so 
but it has Dicom.Native-linux64.so in folder `./runtimes/linux-x64/native/`

**Comment by jaime-olivares** [comment]
The other option is that indeed it is not finding "one of its dependencies"

**Comment by 1009058470** [comment]
Should i need to install some thing on centos for its dependencies?

**Comment by 1009058470** [comment]
> The other option is that indeed it is not finding "one of its dependencies"

yes it truely has some thing losing 
`ldd ./runtimes/linux-x64/native/Dicom.Native-linux64.so 
./runtimes/linux-x64/native/Dicom.Native-linux64.so: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by ./runtimes/linux-x64/native/Dicom.Native-linux64.so)
./runtimes/linux-x64/native/Dicom.Native-linux64.so: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./runtimes/linux-x64/native/Dicom.Native-linux64.so)
./runtimes/linux-x64/native/Dicom.Native-linux64.so: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./runtimes/linux-x64/native/Dicom.Native-linux64.so)
./runtimes/linux-x64/native/Dicom.Native-linux64.so: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./runtimes/linux-x64/native/Dicom.Native-linux64.so)
	linux-vdso.so.1 =>  (0x00007ffec55f0000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f996b181000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f996ae7f000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f996ac69000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f996a89b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f996b489000)
`

but how i can get 
- `GLIBC_2.29'
- 'GLIBCXX_3.4.26'
- 'CXXABI_1.3.9' 
- 'GLIBCXX_3.4.21'

**Comment by jaime-olivares** [comment]
Hi again,

We confirmed that version 5.0 was being compiled with an Ubuntu 20 agent, which caused a change in the c/c++ dependencies. This was affecting our own implementations in Ubuntu 18.
We have forced our build pipeline to use Ubuntu 18 (as before), and the required c/c++ libraries are back gcc & g++ (v7.4)
I hope this solves your problem, otherwise those tools may be missing in our OS, and you have to find how to install them.

Please use the new nuget version: https://www.nuget.org/packages/fo-dicom.Codecs/
