### ISSUE TITLE
Not able to compress Dicom file size. 

### ISSUE THREAD

**Issue by Dash-Uttam** [Efferent-Health/fo-dicom.Codecs#17]
Hello,

I have more than 4 thousand jpeg images in folder and I am creating dicom file from it. Now the issue is the size of 4 thousand images in folder is only 3 mb but when dicom file is created it gone to 2 gb. This is the issue. Please help in that, I have used latest Codec version that is Codec 5.2. below are the code. 

                        DicomDataset ds = new DicomDataset();
                        ds.AddOrUpdate(DicomTag.BitsAllocated, (ushort)8);
                        ds.Add(DicomTag.SOPClassUID, DicomUID.SecondaryCaptureImageStorage);
                        if (StudyID.Any() && !string.IsNullOrEmpty(StudyID[0]))
                        {
                            ds.Add(DicomTag.StudyInstanceUID, StudyID[0]);
                            ds.Add(DicomTag.SeriesInstanceUID, SeriesId[0]);
                            ds.Add(DicomTag.SOPInstanceUID, DicomUID.Generate());
                            ds.Add(DicomTag.PatientID, PID[0]);
                            ds.Add(DicomTag.AccessionNumber, AcnNumber[0]);
                        }
                        else
                        {
                            ds.Add(DicomTag.StudyInstanceUID, DicomUID.Generate());
                            ds.Add(DicomTag.SeriesInstanceUID, DicomUID.Generate());
                            ds.Add(DicomTag.SOPInstanceUID, DicomUID.Generate());
                            ds.Add(DicomTag.PatientID, patientDetailsModelForDicom.PatientId);
                            ds.Add(DicomTag.AccessionNumber, patientDetailsModelForDicom.AccessionNumber);
                        }
                        ds.Add(DicomTag.PatientName, patientDetailsModelForDicom.PatientName);
                        ds.Add(DicomTag.PatientSex, patientDetailsModelForDicom.Gender);
                        ds.Add(DicomTag.PatientBirthDate, patientDetailsModelForDicom.PatientBirthDate);
                        ds.Add(DicomTag.StudyDate, DateTime.Now);
                        ds.Add(DicomTag.StudyTime, DateTime.Now);

                        DicomPixelData pixelData = DicomPixelData.Create(ds, true);
                        pixelData.BitsStored = 8;
                        pixelData.SamplesPerPixel = 3;
                        pixelData.HighBit = 7;
                        pixelData.PixelRepresentation = 0;
                        pixelData.PlanarConfiguration = 0;
                        //pixelData.PixelRepresentation = PixelRepresentation.Unsigned;
                        //pixelData.PlanarConfiguration = PlanarConfiguration.Interleaved;

                        //ds.Add(DicomTag.LossyImageCompression, "01");
                        //ds.Add(DicomTag.LossyImageCompressionMethod, "ISO_10918_1");

                        int i = 0;
                        foreach (var files in model.Files)
                        {
                            Bitmap bitmap;
                            using (var ms = new MemoryStream(model.Files[i].Media))
                            {
                                bitmap = new Bitmap(ms);
                            }
                            byte[] pixels = GetPixels(bitmap);
                            MemoryByteBuffer buffer = new MemoryByteBuffer(pixels);
                            ds.AddOrUpdate(DicomTag.PhotometricInterpretation, PhotometricInterpretation.Rgb.Value);
                            ds.AddOrUpdate(DicomTag.BitsAllocated, (ushort)8);

                            ds.AddOrUpdate(DicomTag.Rows, (ushort)bitmap.Height);
                            ds.AddOrUpdate(DicomTag.Columns, (ushort)bitmap.Width);
                            ds.AddOrUpdate(DicomTag.InstanceNumber, "1");

                            //var fragment = new DicomOtherByteFragment(DicomTag.PixelData);
                            //fragment.Fragments.Add(EmptyBuffer.Value);
                            //fragment.Fragments.Add(EvenLengthBuffer.Create(new MemoryByteBuffer(pixels)));

                            pixelData.AddFrame(buffer);
                            i++;
                        }
                        

                        DicomDataset sqContent = new DicomDataset(); //Content of the sequence
                        sqContent.Add(DicomTag.Modality, "CT");
                        sqContent.Add(DicomTag.ScheduledProcedureStepStartDate, DateTime.Now.Date);

                        DicomSequence sq = new DicomSequence(DicomTag.ScheduledProcedureStepSequence, sqContent); // Create 
                        sequence, add content
                        ds.AddOrUpdate(sq); //Add sequence to main dataset

                        DicomFile file = new DicomFile();
                        file.Dataset.Add(ds); //Add main dataset to DicomFile
                        Random r = new Random();

                        fileName = Path.Combine(DicomFolderPath, r.Next(10000) + ".dcm");

                        file.FileMetaInfo.TransferSyntax = DicomTransferSyntax.JPEG2000Lossless; //Specify transfer syntax

                        // file = file.Clone(DicomTransferSyntax.JPEGProcess1);
                        file.Save(fileName); //Save file to disk

                        await client.AddRequestAsync(new DicomCStoreRequest(fileName));
                        await client.SendAsync();

When i see the file size after file.save(fileName); it was 2 gb. and it's giving error "Non-negative number required.\r\nParameter name: offset" So this is the issue. 

Please help into that. Thank you in advance.

**Comment by cbeltran1306** [comment]
Hello,
I give you a code example, which you want to do.
                
                        DicomDataset ds = new DicomDataset(); //by default transferSyntax ExplicitVRLittleEndian
                        ds.AddOrUpdate(DicomTag.BitsAllocated, (ushort)8);
                        ds.Add(DicomTag.SOPClassUID, DicomUID.SecondaryCaptureImageStorage);
                        if (StudyID.Any() && !string.IsNullOrEmpty(StudyID[0]))
                        {
                            ds.Add(DicomTag.StudyInstanceUID, StudyID[0]);
                            ds.Add(DicomTag.SeriesInstanceUID, SeriesId[0]);
                            ds.Add(DicomTag.SOPInstanceUID, DicomUID.Generate());
                            ds.Add(DicomTag.PatientID, PID[0]);
                            ds.Add(DicomTag.AccessionNumber, AcnNumber[0]);
                        }
                        else
                        {
                            ds.Add(DicomTag.StudyInstanceUID, DicomUID.Generate());
                            ds.Add(DicomTag.SeriesInstanceUID, DicomUID.Generate());
                            ds.Add(DicomTag.SOPInstanceUID, DicomUID.Generate());
                            ds.Add(DicomTag.PatientID, patientDetailsModelForDicom.PatientId);
                            ds.Add(DicomTag.AccessionNumber, patientDetailsModelForDicom.AccessionNumber);
                        }
                        ds.Add(DicomTag.PatientName, patientDetailsModelForDicom.PatientName);
                        ds.Add(DicomTag.PatientSex, patientDetailsModelForDicom.Gender);
                        ds.Add(DicomTag.PatientBirthDate, patientDetailsModelForDicom.PatientBirthDate);
                        ds.Add(DicomTag.StudyDate, DateTime.Now);
                        ds.Add(DicomTag.StudyTime, DateTime.Now);

                        DicomPixelData pixelData = DicomPixelData.Create(ds, true);
                        pixelData.BitsStored = 8;
                        pixelData.SamplesPerPixel = 3;
                        pixelData.HighBit = 7;
                        pixelData.PixelRepresentation = 0;
                        pixelData.PlanarConfiguration = 0;
                        //pixelData.PixelRepresentation = PixelRepresentation.Unsigned;
                        //pixelData.PlanarConfiguration = PlanarConfiguration.Interleaved;

                        //ds.Add(DicomTag.LossyImageCompression, "01");
                        //ds.Add(DicomTag.LossyImageCompressionMethod, "ISO_10918_1");

                        int i = 0;
                        foreach (var files in model.Files)
                        {
                            Bitmap bitmap;
                            using (var ms = new MemoryStream(model.Files[i].Media))
                            {
                                bitmap = new Bitmap(ms);
                            }
                            byte[] pixels = GetPixels(bitmap);
                            MemoryByteBuffer buffer = new MemoryByteBuffer(pixels);
                            ds.AddOrUpdate(DicomTag.PhotometricInterpretation, PhotometricInterpretation.Rgb.Value);
                            ds.AddOrUpdate(DicomTag.BitsAllocated, (ushort)8);

                            ds.AddOrUpdate(DicomTag.Rows, (ushort)bitmap.Height);
                            ds.AddOrUpdate(DicomTag.Columns, (ushort)bitmap.Width);
                            ds.AddOrUpdate(DicomTag.InstanceNumber, "1");

                            //var fragment = new DicomOtherByteFragment(DicomTag.PixelData);
                            //fragment.Fragments.Add(EmptyBuffer.Value);
                            //fragment.Fragments.Add(EvenLengthBuffer.Create(new MemoryByteBuffer(pixels)));

                            pixelData.AddFrame(buffer);
                            i++;
                        }
                        
                        // if you do this
                        // file.FileMetaInfo.TransferSyntax = DicomTransferSyntax.JPEG2000Lossless; //this is wrong
                        
                        // you should do this
                        var jpeg2000lossless = new DicomFile(ds).Clone(DicomTransferSyntax.JPEG2000Lossles);
                        jpeg2000lossless.Save("jpeg2000lossless.dcm");
                        
                        Random r = new Random();
                        fileName = Path.Combine(DicomFolderPath, r.Next(10000) + ".dcm");
                        
                        // or if you want to get transfer syntax JPEGProcess1
                        var file = new DicomFile(ds).Clone(DicomTransferSyntax.JPEGProcess1);
                        file.Save(fileName); //Save file to disk
                        ...
