### ISSUE TITLE
Multi-frame JPEG images with odd frame size get extra padding bytes

### ISSUE THREAD

**Issue by mrbean-bremen** [Efferent-Health/fo-dicom.Codecs#20]
This is basically a copy of https://github.com/fo-dicom/fo-dicom/issues/1300, you may refer to that issue for details.
If a multi-frame image encoded in a JPEG transfer syntax is converted into a non-copressed transer syntax, and the individual frames have an odd size, in the resulting image a padding byte is inserted after each frame. I'm not completely sure if this shall be handled here and not in `fo-dicom`, but it looks that way for me. 

More details: as far as I understand, multi-frame JPEG images are decoded in `DicomJpegNativeCode.Decode`, specifically in this loop:
```cs
            JpegNativeCodec codec = GetCodec(precision, jparams);
            for (int frame = 0; frame < oldPixelData.NumberOfFrames; frame++)
            {
                codec.Decode(oldPixelData, newPixelData, jparams, frame);
            }
```
The actual decoding happens in `JpegCodec.Decode`, where odd frame size is handled:
```cs
        int num1 = this.Bits != 8 ? Convert.ToInt32((long) dinfo.output_width * (long) dinfo.output_components * 2L) : Convert.ToInt32((long) dinfo.output_width * (long) dinfo.output_components * 2L / 2L);
        int int32_1 = Convert.ToInt32((long) num1 * (long) dinfo.output_height);
        if ((uint) (int32_1 % 2) > 0U)
          ++int32_1;
        pinnedByteArray2 = new PinnedByteArray(int32_1);
```
and `pinnedByteArray2` is added to the new pixel data in the end.
If this does what I think, it will add a padding byte to each frame in a multi-frame image, which is invalid. There shall only be a single padding byte at the end of all frames if needed.

**Comment by jaime-olivares** [comment]
This is solved.

You will need to use the last nuget version 5.1 (https://www.nuget.org/packages/fo-dicom.Codecs/ )

**Comment by mrbean-bremen** [comment]
Ok, thank you!
