### ISSUE TITLE
Not possible to set progression order on DicomJpeg2000Codec

### ISSUE THREAD

**Issue by Spinpoo** [Efferent-Health/fo-dicom.Codecs#21]
When using the Clone function to convert a dicom dataset to Jpeg2000 it is not possible to set the OBJ_PROG_ORDER which is always set to LRCP.

It would be nice if this could be set in the DicomJpeg2000Params object.

**Comment by jaime-olivares** [comment]
We are already working on this...

**Comment by jaime-olivares** [comment]
Hi, we have added the possibility to set this parameter, have a look at: https://github.com/Efferent-Health/fo-dicom.Codecs/blob/77269998403dba29300777d600810b8f2e5fdddb/Codec/DicomJpeg2000Codec.cs#L424 

You will need to use the last nuget version 5.1 (https://www.nuget.org/packages/fo-dicom.Codecs/ )
