### ISSUE TITLE
System.AccessViolationException thrown in DicomTranscoder.Encode for JPEG-LS transfer syntaxes

### ISSUE THREAD

**Issue by p33215** [Efferent-Health/fo-dicom.Codecs#23]
When doing operations

var file = DicomFile.Open(filename);
var clonedFile = file.Clone(transferSyntax);

on any file of the fo-dicom.codecs 'Acceptance tests' files using fo-dicom 5.0.2, fo-dicom.Codecs 5.1.0 and .NET framework 4.8, there is an exception thrown for certain JPEG transfer syntax types:
 _System.AccessViolationException
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
 at System.Array.Resize[T](T[]& array, Int32 newSize)
   at FellowOakDicom.Imaging.NativeCodec.DicomJpegLsNativeCodec.Encode(DicomPixelData oldPixelData, DicomPixelData newPixelData, DicomCodecParams parameters)
   at FellowOakDicom.Imaging.Codec.DicomTranscoder.Encode(DicomDataset oldDataset, DicomTransferSyntax outSyntax, IDicomCodec codec, DicomCodecParams parameters)
   at FellowOakDicom.Imaging.Codec.DicomTranscoder.Transcode(DicomDataset dataset)_

Failing 'transferSyntax':
 DicomTransferSyntax.JPEGLSLossless 
 DicomTransferSyntax.JPEGLSNearLossless
Passing 'transferSyntax':
 DicomTransferSyntax.JPEG2000Lossless 
 DicomTransferSyntax.JPEG2000Lossy
 DicomTransferSyntax.JPEGProcess1
 DicomTransferSyntax.JPEGProcess14 
 DicomTransferSyntax.JPEGProcess14SV1
 DicomTransferSyntax.JPEGProcess2_4
 DicomTransferSyntax.RLELossless

It seems like it also happens when using .NET framework 4.8 but not when using .NET Core.

**Comment by jaime-olivares** [comment]
We will review soon and try to reproduce.

The unique usage of Array.Resize is here: 
<img width="555" alt="image" src="https://user-images.githubusercontent.com/6194083/221043280-bd642963-d039-444d-ae54-9f4c29f5847c.png">

**Comment by cbeltran1306** [comment]
This issue has been solved with version **5.10.5**, which is already published in nuget
