### ISSUE TITLE
Heap corruption on compressing a certain image to JPEG2000 Lossy

### ISSUE THREAD

**Issue by mrbean-bremen** [Efferent-Health/fo-dicom.Codecs#24]
This is another spin-off for a [fo-dicom issue](https://github.com/fo-dicom/fo-dicom/issues/1209) filed by @[yadavvirus](https://github.com/yadavvirus). 
If compressing the given [DICOM file](https://github.com/fo-dicom/fo-dicom/files/7983730/anny.zip) (MONOCHROME2, 16 bit), a heap corruption occurs in the codec code. Can easily be reproduced in master by substituting `test16bits.dcm` with the given file and running the `PerformTranscode16bits` unit test. 

If I try to debug this (run under Windows, using .NET 5), it crashes in the OpenJPEG code in `j2k_encode`, more specificaly in the call to `tcd_free_encode` in this line (line 384):
```cpp
     opj_free(prc->cblks.enc[cblkno].data - 2);
```
This line causes a heap corruption error (`CRT detected that the application wrote to memory after end of heap buffer`).

As mentioned by the issue author, compressing the image using the leadtools codec [works fine](https://github.com/fo-dicom/fo-dicom/files/8008022/xray.zip).

**Comment by kundanashish** [comment]
Hi @cbeltran1306 
This issue doesn't seems to be fixed. I am using the latest version 5.14.2
the sample image and code are as below

[image-000001.zip](https://github.com/user-attachments/files/16353127/image-000001.zip)

DicomFile dicomFile = await DicomFile.OpenAsync("inputfilepath");
var codecParams = new FellowOakDicom.Imaging.NativeCodec.DicomJpeg2000Params { Rate = 20};
DicomFile compressed = dicomFile.Clone(DicomTransferSyntax.JPEG2000Lossy, codecParams);
await compressed.SaveAsync("outfilepath");

It would be great help if you can take a look.
Thanks
