### ISSUE TITLE
Photometric Interpretation Question potential issue

### ISSUE THREAD

**Issue by gofal** [Efferent-Health/fo-dicom.Codecs#27]
On fo-dicom project, this issue was raised by @BobSter3000: https://github.com/fo-dicom/fo-dicom/issues/1456

When fo-dicom converts a color image from JPEG Lossless (.70) to JPEG Baseline(.50) the Photometric Interpretation changes from RGB to YBR_FULL. Looking at the standard PS3.5 Table 8.2.1-1 it shows YBR_FULL_422 to be valid for JPEG Baseline. Shouldn't fo-dicom be using YBR_FULL_422?

**Comment by jaime-olivares** [comment]
This has been solved with commit https://github.com/Efferent-Health/fo-dicom.Codecs/commit/1774ae84596a43b74f9402e1b5890f5ff11d9820

Will be published soon in nuget

**Comment by jaime-olivares** [comment]
Fixed and published in nuget: https://www.nuget.org/packages/fo-dicom.Codecs/
