### ISSUE TITLE
M1 Mac (arm) support?

### ISSUE THREAD

**Issue by Hackmodford** [Efferent-Health/fo-dicom.Codecs#28]
Does this support the arm architecture for macos?

**Comment by RyGuyCompSci** [comment]
+1 on this

**Comment by jaime-olivares** [comment]
ARM support is still in the backlog. Not a trivial task for sure.

**Comment by jaime-olivares** [comment]
The following work item is split into several steps:
- [ ] Rename folder and filenames to accommodate different OS and architectures (win, linux, osx, x64, arm64)
- [ ] Unify CMakeLists files for all POSIX targets
- [ ] Enable compilation settings for osx-arm64 and linux-arm64 in CMakeLists
- [ ] Create pipeline jobs for both new targets
- [ ] Update the documentation (README)

**Comment by jaime-olivares** [comment]
Closing after testing on a real Mac with M1. Published in nuget with version 5.10.0
