### ISSUE TITLE
Can't decode Transfer syntax MPEG2 MainProfile / Main Level

### ISSUE THREAD

**Issue by udiatcimd** [Efferent-Health/fo-dicom.Codecs#30]
Hi!

I'm need to decode files with transferSyntax MPEG2MainProfile@MainLevel with photometric interpretation YBR_PARTIAL_420 but I always get the same error:

**"FellowOakDicom.Imaging.Codec.DicomCodecException: 'Decoding dataset with transfer syntax: MPEG2 Main Profile / Main Level is not supported.'"**

Is this type of transferSyntax  planned to be supported?
Or is there any workaround?

I'm using:
fo-dicom 5.0.3 & fo-dicom.codecs 5.1.0 nuget packages
Framework .Net 4.8

Thank you

**Comment by jaime-olivares** [comment]
This question is out of the scope of fo-dicom.Codecs

We don't encode or decode video content.
