### ISSUE TITLE
FellowOakDicom.Imaging.Codec.DicomCodecException for JPEG Baseline (Process 1)

### ISSUE THREAD

**Issue by cenktrms** [Efferent-Health/fo-dicom.Codecs#32]
Dear community,

We have a problem when we try to convert process 1 dcm file to jpeg. We use the code below to convert it.

`var bitmap = dicomImage.RenderImage(frameNumber).As<System.Drawing.Bitmap>();`

we have try to change the transfer syntax then covnert it but it gives the same error when we try to change transfer syntax.

```
var f = dicomFile.Clone(DicomTransferSyntax.ImplicitVRLittleEndian);
dicomImage = new DicomImage(f.Dataset, frameNumber);
var image = dicomImage.RenderImage(frameNumber);
image.AsClonedBitmap().Save(stream, ImageFormat.Jpeg);
```

Error:
> FellowOakDicom.Imaging.Codehttps://www.githubstatus.com/c.DicomCodecException: 'Decoding dataset with transfer syntax: JPEG Baseline (Process 1): Default Transfer Syntax for Lossy JPEG 8 Bit Image Compression is not supported.'

We have also tried to install C++ directories but it didnt work. Do you have any suggestion ?

Platform: Windows 2019 Server / Windows 11 / Windows 10

Codec Version: 5.1.0
fo-dicom: 5.0.3
.net5.0

**Comment by jaime-olivares** [comment]
Is this happening only with that particular conversion? 
Did you manage to decode or convert other transfer syntaxes?

**Comment by cenktrms** [comment]
The problem is only with "Default Transfer Syntax for Lossy JPEG 8 Bit Image Compression"

I also tried process 14 but it seems fine.

**Comment by jaime-olivares** [comment]
Can you please provide any sample DCM file?

**Comment by cenktrms** [comment]
Yes for sure but I cannot share .dcm from here. What do you suggest how can i share it ?

**Comment by jaime-olivares** [comment]
I think you can use any free DICOM anonymizer and then post here.
For example, this one can be used for free for 7 days: https://www.rubomedical.com/dicom_anonymizer/

**Comment by cenktrms** [comment]
Its already anonymized but github does not support file type to upload. So we transfer link;
https://we.tl/t-ZSkkGw4m0Z

by the way it was working in previous versions of fo-dicom but i cant say which version specifically.

Thank you for your hard works.

**Comment by jaime-olivares** [comment]
ok, got the file. I will give it a try today.

**Comment by cenktrms** [comment]
Thank you so much. Same file is converts perfectly to jpeg with dcmtk. We try to make sure.

**Comment by jaime-olivares** [comment]
FYI. We were able to reproduce the error message. It will take some more days to analyze and resolve.

**Comment by jaime-olivares** [comment]
Hi, @cenktrms 
We have determined that you missed initializing the TranscodeManager as explained in the README: https://github.com/Efferent-Health/fo-dicom.Codecs#usage

Please try again and let us know

**Comment by jaime-olivares** [comment]
@cenktrms please confirm if that was the issue

**Comment by jaime-olivares** [comment]
We are closing this issue as we don't have more evidence.

**Comment by cenktrms** [comment]
I could not test it yet but i have this line of code in my code;

```
            new DicomSetupBuilder()
              .RegisterServices(s => s.AddFellowOakDicom().AddTranscoderManager<FellowOakDicom.Imaging.NativeCodec.NativeTranscoderManager>())
              .RegisterServices(s => s.AddFellowOakDicom().AddImageManager<WinFormsImageManager>())
              .SkipValidation()
              .Build();
```
This is what i have in my code.

**Comment by cbeltran1306** [comment]
Hi @cenktrms, please share us a test project where you got the error.

**Comment by cenktrms** [comment]
I have manage test solution for you. I would really appreciate it if you look deeper. 

Sincerely,

[https://github.com/cenktrms/FODICOMTEST/tree/main](url)

**Comment by cbeltran1306** [comment]
Hi @cenktrms, there is an issue in your test, it is fixed if you change this part in your code as below.

    new DicomSetupBuilder()
              .RegisterServices(s => s.AddFellowOakDicom().AddImageManager<WinFormsImageManager>().AddTranscoderManager<NativeTranscoderManager>())
              .Build();

**Comment by cenktrms** [comment]
Thank you i tried it seems to be working just fine. I should be better if you mention it in docs. If you do we couldnt find it.

Thank you for your hard work. ☺️
