### ISSUE TITLE
Failing rendering acceptance tests?

### ISSUE THREAD

**Issue by jovinson-ms** [Efferent-Health/fo-dicom.Codecs#33]
Looking through the release page, it shows that Rendering acceptance tests have been failing in every release since https://github.com/Efferent-Health/fo-dicom.Codecs/releases/tag/v5.0.0.0-beta2. Are these tests stale, or is this a regression?

**Comment by jaime-olivares** [comment]
Hi @jovinson-ms 
Thanks for pointing that out. We will give it a revision.

**Comment by jaime-olivares** [comment]
This is solved. A deprecated library caused it. Now using ImageSharp.
