### ISSUE TITLE
Jpeg missing end tag FFD9

### ISSUE THREAD

**Issue by cocosip** [Efferent-Health/fo-dicom.Codecs#37]
```c#
var dicomfile = await DicomFile.OpenAsync("D:\\222.dcm");
var dicomImage = new DicomImage(dicomfile.Dataset).RenderImage();
```
When i try to render image ,get some error 
`JPEG 12 bit codec unable to perform reading scanlines pixel data`

I find jpeg data missing  end tag  FF D9. 
Is there a way to deal with this problem?

**Comment by jaime-olivares** [comment]
Hi @cocosip,
Can you send an anonymized dcm sample?

**Comment by jaime-olivares** [comment]
We will close this issue soon, as we don't have enough evidence to help evaluate.
