### ISSUE TITLE
Problem with encoding DoseInfo with JPEG2000 (both Lossless/Lossy)

### ISSUE THREAD

**Issue by bakhtvar** [Efferent-Health/fo-dicom.Codecs#49]
Ensure you are reporting a defect related to encoding/decoding pixel data.

**Describe the bug**
The output image with DicomFile.Open().Clone(DicomTransferSyntacx.LosslessJprg2000), on Siemens DoseInfo files are just problematic.

**To Reproduce**
DicomFile.Open().Clone(DicomTransferSyntacx.LosslessJprg2000) on the attached file.

**Screenshots**
Sometimes a screenshot helps to understand how an image is distorted
Original File (JpegLossless)
![image](https://github.com/Efferent-Health/fo-dicom.Codecs/assets/5196447/4ed8f72d-7f80-4258-8b3b-9c61883e3e52)
Changed to Jpeg2000Lossless
![image](https://github.com/Efferent-Health/fo-dicom.Codecs/assets/5196447/0614be20-987c-44c3-8f10-1c04f2848a9e)

**Environment:**
Latest version of the lib.

[DoseInfo-Problem-2000.zip](https://github.com/Efferent-Health/fo-dicom.Codecs/files/12063983/DoseInfo-Problem-2000.zip)

**Comment by cbeltran1306** [comment]
Hi @bakhtvar, this bug has been solved, please use the lastes stable nuget https://www.nuget.org/packages/fo-dicom.Codecs/5.13.0.
