### ISSUE TITLE
Jpeg2000 Codec applying gets Hanged! on special sized dicom file

### ISSUE THREAD

**Issue by bakhtvar** [Efferent-Health/fo-dicom.Codecs#50]
Ensure you are reporting a defect related to encoding/decoding pixel data.

While one applys Dicom2000 on the attached file. it simply hangs and not returned!

**To Reproduce**
Try to compress Jpeg2000, is hangs. the file has Rows=1144 and Columns=31.
[Big-Small-Sized.zip](https://github.com/Efferent-Health/fo-dicom.Codecs/files/12080857/Big-Small-Sized.zip)

**Comment by cbeltran1306** [comment]
Hi @bakhtvar, can you send us more information about it, in order to reproduce this bug?

**Comment by cbeltran1306** [comment]
We are closing this issue as we do not have more evidence, please use the latest stable nuget https://www.nuget.org/packages/fo-dicom.Codecs/5.12.0.
