### ISSUE TITLE
Another problematic file with Jpeg2000 Encoding

### ISSUE THREAD

**Issue by bakhtvar** [Efferent-Health/fo-dicom.Codecs#51]
Ensure you are reporting a defect related to encoding/decoding pixel data.

**Describe the bug**
The file encoded and turned into ALL white!

**To Reproduce**
var df = DicomFile.Open(@"E:\original.dcm");
df.Clone(DicomTransferSyntax.JPEG2000Lossless).Save(@"E:\original-out.dcm");

![image](https://github.com/Efferent-Health/fo-dicom.Codecs/assets/5196447/78ca989f-38e5-4b20-9a0f-e3dc54f6f776)
original file

![image](https://github.com/Efferent-Health/fo-dicom.Codecs/assets/5196447/d4234b39-06bf-4f14-adce-d6578eb19564)
changed to 2000 and corrupted!

**Environment:**
 - Windows 
 - `fo-dicom.Codecs` 5.10.8
[original.zip](https://github.com/Efferent-Health/fo-dicom.Codecs/files/12345443/original.zip)

**Comment by jaime-olivares** [comment]
To be analyzed next week

**Comment by cbeltran1306** [comment]
Hi @bakhtvar, this issue has been solved, please use the latest nuget version 5.14.3.
https://www.nuget.org/packages/fo-dicom.Codecs/5.14.3
