### ISSUE TITLE
Dicom.Native 0x8007007E

### ISSUE THREAD

**Issue by nutzlastfan** [Efferent-Health/fo-dicom.Codecs#52]
I am converting an Image to JPEGProcess14 an get the following error.

System.DllNotFoundException: "Die DLL "Dicom.Native": Das angegebene Modul wurde nicht gefunden. (Ausnahme von HRESULT: 0x8007007E

The Problem occurred first when updating form 5.9.2 to 5.10.8. When downgrading back to 5.9.2 it works again.
I also tried the beta but the problem still exists.

Hope someone can help me.

Stack trace:
   bei FellowOakDicom.Imaging.NativeCodec.Jpeg.JpegCodec.jpeg_std_error_8(jpeg_error_mgr& err)
   bei FellowOakDicom.Imaging.NativeCodec.Jpeg.JpegCodec.Encode(DicomPixelData oldPixelData, DicomPixelData newPixelData, DicomJpegParams jpegParams, Int32 frame)
   bei FellowOakDicom.Imaging.NativeCodec.DicomJpegNativeCodec.Encode(DicomPixelData oldPixelData, DicomPixelData newPixelData, DicomCodecParams parameters)
   bei FellowOakDicom.Imaging.Codec.DicomTranscoder.Encode(DicomDataset oldDataset, DicomTransferSyntax outSyntax, IDicomCodec codec, DicomCodecParams parameters)
   bei FellowOakDicom.Imaging.Codec.DicomTranscoder.Transcode(DicomDataset dataset)
   bei FellowOakDicom.Imaging.Codec.DicomTranscoder.Transcode(DicomFile file)
   bei DicomHelpers.helpers.converttodicom(String arzt, String we, String description, String studyinstanceuid, String seriesinstanceuid, String orgfilepath, Int32 instance, DicomDataset vdata, Double spacing, DateTime creationdate, Boolean singlepic, Boolean video, String ffmpegpath) in ...

Environment
Fellow Oak DICOM version:
"fo-dicom" Version="5.1.1"
"fo-dicom.Codecs" Version="5.10.8"
OS: Windows 10 x64
Platform: .NET 4.6.2

**Comment by jaime-olivares** [comment]
We will analyze this next week

**Comment by gguimaraes0** [comment]
waiting

**Comment by cbeltran1306** [comment]
Hi @gguimaraes0, can you send us a sample dicom in order to reproduce the issue, please?

**Comment by gguimaraes0** [comment]
[Anonymized.zip](https://github.com/Efferent-Health/fo-dicom.Codecs/files/13355037/Anonymized.zip)
I have more if necessary, the maximum sending limit is 25mb. Problems often occur with exams in the MG modality

**Comment by anishsingh0302** [comment]
I am also facing error after upgrading to latest version of fo-dicom.
fo-dicom.Codecs - version 5.10.8. previous version - 5.10.3

System.DllNotFoundException: Unable to load DLL 'Dicom.Native': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

Stack Trace: 
DicomJpeg2000NativeCodec.Memset(Void* ptr, Int32 value, UInt32 num)
DicomJpeg2000NativeCodec.Decode(DicomPixelData oldPixelData, DicomPixelData newPixelData, DicomCodecParams parameters)
DicomTranscoder.Decode(DicomDataset oldDataset, DicomTransferSyntax outSyntax, IDicomCodec codec, DicomCodecParams parameters)
DicomTranscoder.Transcode(DicomDataset dataset)
DicomTranscoder.Transcode(DicomFile file)

while debugging I could see while cloning the Dicomfile above error is throwing. Please find the snapshot.

![image](https://github.com/Efferent-Health/fo-dicom.Codecs/assets/88501619/4fb8298a-ab71-4355-93e2-d5c3d5c3da73)

is this issue known?

**Comment by cbeltran1306** [comment]
Hi @nutzlastfan , you can use this new nuget version **5.11.0** https://www.nuget.org/packages/fo-dicom.Codecs/5.11.0. Please make sure the native library **Dicom.Native.dll** is in your **bin** folder when you use .NetFramework environment.
