### ISSUE TITLE
Support for Windows 32bit

### ISSUE THREAD

**Issue by pdgmdm** [Efferent-Health/fo-dicom.Codecs#53]
Would it be possible to also add the Windows 32bit platform to supported platforms and include the binaries in the nuget package ?

**Comment by jaime-olivares** [comment]
There are no plans to support 64-bits. The use cases are a few, and the effort is enormous.

**Comment by pdgmdm** [comment]
Hi Jaime, many old systems still use 32bit applications. I managed to build the native codes for win32, simply by add a new configuration to the msvc c++ projects. 
If you ever have time to include this also in the release build, that would be very great!
