### ISSUE TITLE
Plan to support HTJ2K (High-Throughput JPEG 2000)

### ISSUE THREAD

**Issue by bcarthic** [Efferent-Health/fo-dicom.Codecs#54]
Is there a plan to support HTJ2K (High-Throughput JPEG 2000)?

**Refer to formal documentation**
[DICOM Standard -HTJ2K Transfer Syntax
](https://www.dicomstandard.org/news-dir/current/docs/sups/sup235.pdf)

**Provide source code**
Preferred: Fork and create a pull-request if you already tried a solution. That may speed up the adoption.
Less preferred: Provide some code snippet.

**Comment by bcarthic** [comment]
@jaime-olivares

**Comment by jaime-olivares** [comment]
There are not plans yet as there is not an official spec.

The provided document is a draft and there are not transfer syntax UIDs for the new encoding methods.

**Comment by jaime-olivares** [comment]
We are considering the following alternatives for building the HTJ2K codec:

- https://github.com/uclouvain/openjpeg
- https://github.com/osamu620/OpenHTJ2K
- https://github.com/aous72/OpenJPH

If somebody has experience or an opinion on them, please share.

**Comment by mrbean-bremen** [comment]
`pydicom` uses `openjpeg` (via [pylibjpeg-openjpeg](https://github.com/pydicom/pylibjpeg-openjpeg])), which seems to work fine - though this has been added only recently.

**Comment by PantelisGeorgiadis** [comment]
> We are considering the following alternatives for building the HTJ2K codec, as we have now the transfer syntax released and supported in fo-dicom:
> 
> - https://github.com/uclouvain/openjpeg
> - https://github.com/osamu620/OpenHTJ2K
> - https://github.com/aous72/OpenJPH
> 
> If somebody has experience or an opinion on them, please share.
> 

I believe that OpenJPH is the best option.

**Comment by mhmmd7777** [comment]
Any updates?

**Comment by jaime-olivares** [comment]
In development

Sent from my iPhone 14
________________________________

**Comment by jaime-olivares** [comment]
We have made good progress on this. We spent dozens of hours determining how to integrate the HTJ2K C library.
We have built a beta environment with the following published *nuget* packages:

`<PackageReference Include="fo-dicom.Codecs" Version="5.13.0-beta5" />`
`<PackageReference Include="Efferent.fo-dicom" Version="5.2.0" />`

The first one is a beta codec library supporting HTJ2K encoding and decoding **for Intel processors only** at this time.

The second one is a forked version of fo-dicom, including the pertinent transfer syntax UIDs:
- HTJ2KLossless: 1.2.840.10008.1.2.4.201
- HTJ2KLosslessRPCL: 1.2.840.10008.1.2.4.202
- HTJ2K: 1.2.840.10008.1.2.4.203

For testing, we have used the sample images provided by Chris Hafey here: https://github.com/chafey/DICOMHTJ2K/tree/main/test/fixtures 

Please try while we keep going.

**Comment by jaime-olivares** [comment]
We have added support for ARM architecture in Linux and macOS. Use the following packages:
````
<PackageReference Include="fo-dicom.Codecs" Version="5.13.0-beta6" />
<PackageReference Include="Efferent.fo-dicom" Version="5.2.0" />
````

**Comment by jaime-olivares** [comment]
Support for HTJ2K is now official !
Use fo-dicom version 5.1.3 and fo-dicom.Codecs 5.14.0
