### ISSUE TITLE
The so file built in raspberry pi is not healthy and does not work properly

### ISSUE THREAD

**Issue by dantemayson** [Efferent-Health/fo-dicom.Codecs#58]
hi,It corrects the file when building, but when using the so file in the test project, it does not encode the DYCOM file correctly.
Raspberry Pi 4 Model B
cpu :  Quad core Cortex-A72 (ARM v8) 64-bit SoC @ 1.8GHz
os : ubuntu 22.04
arch : arm64

**Comment by jaime-olivares** [comment]
We don't have a way to diagnose that platform

**Comment by jaime-olivares** [comment]
in fact, this seems to require linux for arm64. We don't have immediate plans but may consider anytime in the near future.

**Comment by dantemayson** [comment]
Thank you for your guidance. If you guide me on what to do to get the so version on my raspberry, I can do these things and get the output and give pr

**Comment by jaime-olivares** [comment]
This issue will be solved along with #62 

Please follow up that one.
