### ISSUE TITLE
Unable to load DLL 'Dicom.Native': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

### ISSUE THREAD

**Issue by anishsingh0302** [Efferent-Health/fo-dicom.Codecs#59]
I am also facing  error after upgrading to latest version of fo-dicom.
fo-dicom.Codecs - version 5.10.8

System.DllNotFoundException: Unable to load DLL 'Dicom.Native': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

Stack Trace: 
DicomJpeg2000NativeCodec.Memset(Void* ptr, Int32 value, UInt32 num)
DicomJpeg2000NativeCodec.Decode(DicomPixelData oldPixelData, DicomPixelData newPixelData, DicomCodecParams parameters)
DicomTranscoder.Decode(DicomDataset oldDataset, DicomTransferSyntax outSyntax, IDicomCodec codec, DicomCodecParams parameters)
DicomTranscoder.Transcode(DicomDataset dataset)
DicomTranscoder.Transcode(DicomFile file)

Anyone of them found any solution?

**Environment:**
 - OS: Windows X64
 - fo-dicom - version 5.1.1
 - `fo-dicom.Codecs` nuget package version: 5.10.8

**Comment by cbeltran1306** [comment]
Hi @anishsingh0302, how did you get the issue, or what was the previous version you used?

**Comment by anishsingh0302** [comment]
fo-dicom.Codecs of my Previous version was 5.10.3.

**Comment by jaime-olivares** [comment]
This doesn't seem to be a defect in the library, but an issue in your source code.
Please ask in StackOverflow with the tag [fo-dicom]

**Comment by anishsingh0302** [comment]
@cbeltran1306  @jaime-olivares I have strongly believe it is defect in library because while debugging I could see while cloning the Dicomfile above error is throwing. Please find the snapshot.

![image](https://github.com/Efferent-Health/fo-dicom.Codecs/assets/88501619/722e87cf-ccbc-4024-a0b5-f3be92434d04)

**Comment by cbeltran1306** [comment]
Hi @anishsingh0302, you can use this new nuget version **5.11.0** https://www.nuget.org/packages/fo-dicom.Codecs/5.11.0. Please make sure the native library **Dicom.Native.dll** is in your **bin** folder when you use **.NetFramework** environment.
