### ISSUE TITLE
Linux arm64 support 

### ISSUE THREAD

**Issue by cocosip** [Efferent-Health/fo-dicom.Codecs#62]
When run in linux arm64, it will get an error "Unsupported OS Platform" .
Checked the corresponding [source code](https://github.com/Efferent-Health/fo-dicom.Codecs/blob/a8e8756b39fa3fcff88af0de034aa85a5204f22c/Codec/Platform.cs#L6) , It seems to only support win64, linux64, osx64, osx_arm64

**Comment by cocosip** [comment]
Can someone provide some help? @jaime-olivares

**Comment by cbeltran1306** [comment]
Hi @cocosip, you can use this new nuget version 5.12.0 https://www.nuget.org/packages/fo-dicom.Codecs/5.12.0.
