### ISSUE TITLE
Bug of package 'FellowOakDicom.Imaging.NativeCodec'.

### ISSUE THREAD

**Issue by SnowCats** [Efferent-Health/fo-dicom.Codecs#64]
**Bug description**
I imported packages 'FellowOakDicom.Imaging.NativeCodec' in my project. It will generate some temp files. 

**Screenshots**
![image](https://github.com/Efferent-Health/fo-dicom.Codecs/assets/15209050/c2251b89-d028-41a8-8a07-5f56b8f74c10)

**Environment:**
 - OS: Both `Windows 11` and `Ubuntu 20`
 - `fo-dicom` nuget package version: v5.1.2
 - `fo-dicom.Codecs` nuget package version: v5.10.0.0

**Comment by jaime-olivares** [comment]
This issue doesn't seem to be related to this library. 

We have examined the nuget package and it only contains single binary files for each platform.

Please check the Nuget project (https://github.com/NuGet/Home), which contains several similar reports.
