### ISSUE TITLE
strongly named assembly

### ISSUE THREAD

**Issue by KavyaAlur** [Efferent-Health/fo-dicom.Codecs#65]
We are using fo-dicom codec nuget package and referencing it from an assembly which is strongly named. As codec assemblies are not strongly named, it throws a runtime error because of a .net limitation which specifies all assemblies referenced from a strongly named one should also be strongly named. Would it be possible to get strongly named assembly which can be used?

**Comment by jaime-olivares** [comment]
Version 5.14.1 is now signed
