### ISSUE TITLE
Slowness Issue When Changing all Tomosynthesis File Compression to JPEG 2000 Lossless

### ISSUE THREAD

**Issue by enasbond** [Efferent-Health/fo-dicom.Codecs#66]
In certain scenarios, particularly with larger-sized images exceeding a width of 2000 pixels and a significant number of frames (e.g., 60), a notable slowness is observed when transitioning the tomosynthesis file compression from any compression type to JPEG 2000 lossless. This delay significantly impacts the efficiency of the compression process, with the operation taking more than 4 minutes to complete.

**Comment by cbeltran1306** [comment]
Hello @enasbond, could you provide us some dicom samples that you tested, please?

**Comment by cbeltran1306** [comment]
Please use the latest nuget version https://www.nuget.org/packages/fo-dicom.Codecs/5.13.0.
We have upgraded the OpenJPEG library to **v2.5.2**, indeed the performance JPEG2000 codecs are highly enhanced. 

**The encoding process is 4 times faster and decoding 1.5 times faster as before, tested dicom files with multiple frames (640 Mb approx.).**

**Comment by enasbond** [comment]
Thank you for the update and for providing the latest NuGet package link. It's great to hear about the significant performance improvements with the upgraded OpenJPEG library.

We appreciate the effort in enhancing the JPEG2000 codecs. The increase in encoding and decoding speeds will be very beneficial for our projects, especially with large DICOM files.

Thanks again for the valuable information and your continued support.

I will check it with my study and confirm you
