### ISSUE TITLE
run err

### ISSUE THREAD

**Issue by wjm23714** [Efferent-Health/fo-dicom.Codecs#67]
version `GLIBC_2.29' not found (required by /wjm/linux-x64/Dicom.Native.so)

**Comment by wjm23714** [comment]
in system ubunut 16.04

**Comment by jaime-olivares** [comment]
Ubuntu 16.04 is a deprecated version. Please use Ubuntu 18+.
Otherwise, you would have to install that version of _glibc_ manually, which seems to be a very dangerous task.
Anyway, the issue/solution is external to this library and we cannot do anything about it.
