### ISSUE TITLE
Crash when encoding to JPEGLSLossless or JPEGLSNearLossless

### ISSUE THREAD

**Issue by TheMcCann7** [Efferent-Health/fo-dicom.Codecs#68]
**Describe the bug**
When encoding to JPEGLSLossless or JPEGLSNearLossless, it will seemingly crash at random times.  It's not always the same image in an image series that will crash.  This doesn't happen with the JPEG2000 encoders on the same image series.  I was testing with standard MRI and CT series.

**To Reproduce**
Iterate through each image in an image series using fo-dicom, and then re-encode each to JPEG-LS.  Eventually, it will catastrophically crash with no exception that I can catch in .NET.

Example code:
``` cs
DicomFile dicomFile = DicomFile.Open(dicomFilePath, FileReadOption.ReadAll);
compressedDicomFile = dicomFile.Clone(DicomTransferSyntax.JPEGLSLossless);
```

If I perform a `GC.Collect()` between each re-encoding, it actually works fine.  This led me to be suspicious of managed memory being used by unmanaged code that wasn't being properly pinned or fixed with the garbage collector.  After glancing through the `Encode()` method in https://github.com/Efferent-Health/fo-dicom.Codecs/blob/master/Codec/DicomJpegLsCodec.cs, I think there might be some memory management issues that were introduced by the introduction of the `ArrayPool`.  For example, `newJpegData` is being rented from the `ArrayPool` multiple times, but is only returned once at the end of the method.  I tried going back to a version before the `ArrayPool` changes, but they don't support .NET Framework, so I couldn't verify if that was the issue.

**Environment:**
 - OS: Windows 11
 - `fo-dicom` nuget package version: 5.1.2
 - `fo-dicom.Codecs` nuget package version: 5.12.0
- Using .NET Framework 4.8.

**Comment by aerik** [comment]
Did you ever get any further on this, or are you just calling GC.Collect() ?

**Comment by TheMcCann7** [comment]
I decided to use a different encoding (`JPEGProcess14SV1`).  It's not as good as `JPEGLSLossless`, but I feel a lot safer using it instead of relying on `GC.Collect()`.

**Comment by cbeltran1306** [comment]
Hello @TheMcCann7, can you provide us your sample project which you tested in order to reproduce the issue?

**Comment by cbeltran1306** [comment]
Hi @TheMcCann7, this bug has been solved, please use the lastest stable nuget https://www.nuget.org/packages/fo-dicom.Codecs/5.14.0.5.

**Comment by TheMcCann7** [comment]
This seems to have fixed it.  Thanks!
