### ISSUE TITLE
Plan to update the OpenJPEG library

### ISSUE THREAD

**Issue by jaime-olivares** [Efferent-Health/fo-dicom.Codecs#69]
We have been using a now-outdated version of [OpenJPEG](https://github.com/uclouvain/openjpeg) (2011) for the last six years. 
It is not easy to change it because there are specific dependencies between the C# and C++ code, with high sensitivity to changes in method names and signatures. After solving that, we have to test every platform we support (Windows, Linux, macOS, Intel, ARM).
During this time, we have received several reports of specific DICOM files failing to decode, that we know are solved in the newest versions of OpenJPEG.
It seems it is almost the time for updating the version. It's a bummer that OpenJPEG still doesn't support HTJ2K encoding (read https://github.com/uclouvain/openjpeg/issues/1487) but we hope it will incorporated soon and can be added without impacting our source code significantly.

**Comment by jaime-olivares** [comment]
Associated branch: https://github.com/Efferent-Health/fo-dicom.Codecs/tree/Upgrade-OpenJPEG-library-to-v2.5.2

**Comment by cbeltran1306** [comment]
This enhacement has been included in the new release https://www.nuget.org/packages/fo-dicom.Codecs/5.13.0.
