### ISSUE TITLE
Update documentation about required runtime dependencies dicom.native.dll and Visual C++ Redistributable ver 14

### ISSUE THREAD

**Issue by MrBean2016** [Efferent-Health/fo-dicom.Codecs#72]
If you do an install on a clean Windows you will get the error "Unable to load DLL 'Dicom.Native': The specified module could not be found. (Exception from HRESULT: 0x8007007E)"

I investigated the dependencies using Dependency Walker and I noticed that Vcruntime140.dll is needed. 
Installing Visual C++ Redistributable 14.40.33810.0 solves the issue. ( https://aka.ms/vs/17/release/vc_redist.x64.exe )

This should be listed in the installation instructions.

**Comment by jaime-olivares** [comment]
That has been mentioned multiple times in the fo-dicom repository.

I just added a section in fo-dicom.Codec's README.

**Comment by MrBean2016** [comment]
Great!
