### ISSUE TITLE
To add Release information's from 5.11.0 onwards

### ISSUE THREAD

**Issue by MastanSV** [Efferent-Health/fo-dicom.Codecs#73]
It would be better if you guys update Release info on Release section of  fo-dicom.codecs Github page. 
In nuget page the latest release is 5.13.1, but in github the releases are mentioned till 5.10.0 which will mislead the users.

The Release section of fo-dicom.codecs github page, which am referring is the below link.
https://github.com/Efferent-Health/fo-dicom.Codecs/releases

**Comment by jaime-olivares** [comment]
We are revamping this feature to present more meaningful information, and using GitHub Actions for CI

**Comment by jaime-olivares** [comment]
This is back up.
Releases will be shown since version 5.14
