### ISSUE TITLE
Use transcoder to decode JPEG Lossless DICOM will change the pixel value

### ISSUE THREAD

**Issue by Charlie022802** [Efferent-Health/fo-dicom.Codecs#75]
I'm using fo-dicom 5.1.3 with fo-dicom.Codecs 5.13.4.
The original image's transfer syntax is 1.2.840.10008.1.2.4.70 (JPEG Lossless, Nonhierarchical, First-Order Prediction) as shown below:
![螢幕擷取畫面 2024-07-01 122616](https://github.com/Efferent-Health/fo-dicom.Codecs/assets/45646910/c99b1514-ed86-48cb-a0a3-552b0c6e56be)

After decoding to 1.2.840.10008.1.2.1 (Explicit VR Little Endian), the pixel values change, causing the window level to not match, as shown below:
![螢幕擷取畫面 2024-07-01 122640](https://github.com/Efferent-Health/fo-dicom.Codecs/assets/45646910/054eb854-4d19-4de6-b757-53d00e6e07e5)

The DICOM file can be accessed from here: [https://drive.google.com/file/d/14ngl9HTJf9YrNpdaTSSd3LNDt4QYI2Dt/view?usp=sharing](url)

Why do the pixel values change?

**Comment by jaime-olivares** [comment]
We are still analyzing the issue. It seems the image has been downgraded to 8 bits for an unknown reason. 
So the window level that will show the image should be very low.

**Comment by cbeltran1306** [comment]
Hi @Charlie022802, this problem has been solved, please use the latest nuget version **v5.14.2** https://www.nuget.org/packages/fo-dicom.Codecs/5.14.2.
