### ISSUE TITLE
System.MissingMethodException: Method not found: 'Void Microsoft.VisualStudio.CodeCoverage.Shim.3309670844__coverage_runtime_method__249_19234__(UInt64)'..

### ISSUE THREAD

**Issue by lsqtest811** [Efferent-Health/fo-dicom.Codecs#77]
I have updated fo-dicom from 4.0.5 to 5.1.2 and tried to implement the breaking changes. So after implementing the changes the unit test case is throwing below error 
System.MissingMethodException: Method not found: 'Void Microsoft.VisualStudio.CodeCoverage.Shim.3309670844__coverage_runtime_method__249_19234__(UInt64)'..
  Stack Trace:
      at Processor.ProcessorContext..ctor(String countryISOCode, IList`1 ActiveFeatureToggleKeys)
   at ClinicalExtension_uTest.ProcessingUnitTests.TestInit() in S:\a\1\s\Test\ClinicalExtensionTests\ProcessingUnitTests.cs:line 76
   at InvokeStub_ProcessingUnitTests.TestInit(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)

When I added code to initialize the transcoder then only it starts giving such error otherwise the UTs were passing before.

**Environment:**
 - OS:  x64
 - `fo-dicom` nuget package version: 5.1.2
 - `fo-dicom.Codecs` nuget package version: 5.1.0

**Comment by jaime-olivares** [comment]
How is this related to fo-dicom.Codecs?

**Comment by jaime-olivares** [comment]
Closing as not related

**Comment by lsqtest811** [comment]
new DicomSetupBuilder()
.RegisterServices(s =>
{
    s.AddFellowOakDicom().AddTranscoderManager<NativeTranscoderManager>();
})
.Build();

After adding the above code snippet from fo-dicom.codecs I am getting this error.

**Comment by jaime-olivares** [comment]
Try with the suggested code from the README:

````
new DicomSetupBuilder()
  .RegisterServices(s => s.AddFellowOakDicom().AddTranscoderManager<FellowOakDicom.Imaging.NativeCodec.NativeTranscoderManager>())
  .SkipValidation()
  .Build();
````
