### ISSUE TITLE
Images Corrupted in Cornerstone After Updating to 5.14.2

### ISSUE THREAD

**Issue by enasbond** [Efferent-Health/fo-dicom.Codecs#80]
I have encountered an issue after upgrading [fo-dicom.Codecs] from version 5.12.0 to 5.14.2. When I attempt to change the image compression, the resulting image cannot be viewed in my viewer.

My viewer is built using Cornerstone. You can simulate this issue by trying to load the new image generated from version 5.14.2 in this viewer: (https://www.cornerstonejs.org/live-examples/localcpu).

Please note that the same code and file worked fine using Cornerstone before and version 5.12.0.

This issue is critical for me because I need to use version 5.13.0 for speed optimizations, but I cannot view the images using Cornerstone, even though it worked before.

Sample image (before and after compression to jpeg 2000 lossless and none using version 5.14.2 )

[sample mg.zip](https://github.com/user-attachments/files/16415744/sample.mg.zip)

**Screenshots**

![image](https://github.com/user-attachments/assets/3b67c992-8a20-471f-95ce-1e6cb9295a68)

![image](https://github.com/user-attachments/assets/fb09d7ff-ae5f-4250-9cb6-d309776c7d88)

**Environment:**
 - `fo-dicom` nuget package version: 5.1.3
 - `fo-dicom.Codecs` nuget package version: 5.14.2

**Comment by jaime-olivares** [comment]
We are analyzing at this moment

**Comment by cbeltran1306** [comment]
Hi @enasbond, this issue has been solved, please use the latest nuget version **5.14.3**.
https://www.nuget.org/packages/fo-dicom.Codecs/5.14.3

**Comment by enasbond** [comment]
That sounds great! I just tested it, and it worked perfectly. I'll go ahead and test it on all the remaining cases I have. Thank you so much!

**Comment by enasbond** [comment]
Hi @cbeltran1306 
I tested the new update with my sample files, but unfortunately, most of them became corrupted when converting to JPEG 2000 lossless or even to implicit VR little endian. A new issue also emerged: these corrupted files can’t be opened by other well-known software, as seen in these images.

It's worth noting that all these files worked perfectly fine with version 5.12.0.
[Samples.zip](https://github.com/user-attachments/files/16461765/Samples.zip)

**Comment by cbeltran1306** [comment]
Hi @enasbond, we found the issue, it was minor fix during the JPEG lossless decoding, please use the latest nuget version **5.14.4** => https://www.nuget.org/packages/fo-dicom.Codecs/5.14.4

**Comment by enasbond** [comment]
Thank you so much, @cbeltran1306 , for your quick response. I really appreciate it. I will review it and keep you updated. Thanks again!
