### ISSUE TITLE
Cannot get current processor architecture in .NET 9

### ISSUE THREAD

**Issue by hyperlapse122** [Efferent-Health/fo-dicom.Codecs#83]
**Describe the bug**
[`AssemblyName.ProcessorArchitecture` was deprecated](https://learn.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib0037) and always returns `ProcessorArchitecture.MSIL` in .NET 9.
Due to this change, `Platform.Current` always returns unknown architecture on Windows x64 (It worked on .NET 8). (please refer [to this code using `AssemblyName.ProcessorArchitecture`](https://github.com/Efferent-Health/fo-dicom.Codecs/blob/121edd52b50ea892593276360092e3a09708df9a/Codec/Platform.cs#L35)

There is `RuntimeInformation.ProcessArchitecture` and `RuntimeInformation.OSArchitecture` but I don't know if it can be used for it.

**To Reproduce**
- Create an empty console application with `fo-dicom` and `fo-dicom.Codecs`, and try encode / decode DICOM image.

**Environment:**
 - OS: Windows 11 24H2 (10.0.26100.2314)
 - `fo-dicom` nuget package version: 5.1.4
 - `fo-dicom.Codecs` nuget package version: 5.15.2

**Comment by jaime-olivares** [comment]
We already testing a universal solution in branch [`GetProcessorArchitecture`](https://github.com/Efferent-Health/fo-dicom.Codecs/tree/GetProcessorArchitecture)
