### ISSUE TITLE
Multi-frame image creates drifting frames

### ISSUE THREAD

**Issue by fh-lipweeyeo** [Efferent-Health/fo-dicom.Codecs#84]
I am trying to convert a multi-frame RLE Lossless image into Implicit VR Little Endian.
The Photometric Interpretation is Palette Color.

When I run the following code:

```
public void CreateDicomFile(DicomDataset dicomDataset) 
{
    var inPath = @"C:\temp\multiframe_image0020.dcm";
    var outPath = @"C:\temp\output.dcm";
    var newDicomFile = DicomFile.Open(inPath);
    var result = newDicomFile.Clone(DicomTransferSyntax.ImplicitVRLittleEndian);
    result.Save(outPath);
}
```

I observed frames start to drift (significantly) from the 2nd frame onwards.
![image](https://github.com/user-attachments/assets/d988b089-eed5-41c7-a28f-62eccd1424fe)

This frame drifting issue is only observed if I'm using this native transcoder, did not observed any issue if using the default transcoder from fo Dicom.
[multiframe_image0020.zip](https://github.com/user-attachments/files/17808819/multiframe_image0020.zip)

 - OS: Windows 11 23H2
 - `fo-dicom` nuget package version: 5.1.4
 - `fo-dicom.Codecs` nuget package version: 5.15.2

**Comment by cbeltran1306** [comment]
Hi @fh-lipweeyeo, this issue has been solved, please use the latest version **5.15.4**  (https://www.nuget.org/packages/fo-dicom.Codecs/5.15.4)
